const { chromium } = require('playwright');
const { pathToFileURL } = require('url');
const path = require('path');
const assert = require('assert');
(async () => {
  const browser = await chromium.launch({channel:'msedge',headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[]; page.on('pageerror', e=>errors.push(e.message));
  await page.goto(pathToFileURL(path.join(__dirname,'ember-tide.html')).href);
  await page.waitForFunction(()=>paintedForest.complete && paintedForest.naturalWidth && Art.pending===0);
  assert.equal(await page.title(),'Water Jac and Fire Jay');
  await page.screenshot({path:path.join(__dirname,'title-preview.png')});
  await page.click('#btnSolo');
  await page.locator('.node:not(.locked)').first().click();
  await page.waitForFunction(()=>Game.state==='play');
  await page.keyboard.press('Shift');
  assert.equal(await page.evaluate(()=>Game.active),'water');
  const before=await page.evaluate(()=>Game.level.players.find(p=>p.kind==='water').x);
  await page.keyboard.down('KeyD');
  await page.waitForFunction(x=>Game.level.water.x>x+4,before);
  await page.keyboard.up('KeyD');
  assert.deepEqual(errors,[]);
  assert((await page.evaluate(()=>Game.level.players.find(p=>p.kind==='water').x))>before);
  await page.screenshot({path:path.join(__dirname,'game-preview.png')});
  await page.keyboard.press('KeyP'); assert(await page.evaluate(()=>Game.paused));
  await page.keyboard.press('KeyP'); assert(!(await page.evaluate(()=>Game.paused)));
  await page.keyboard.press('KeyH'); assert(await page.evaluate(()=>Game.showConnections));
  await page.keyboard.press('KeyH'); assert(!(await page.evaluate(()=>Game.showConnections)));
  const collection=await page.evaluate(()=>{
    Game.startLevel(0);
    const l=Game.level,g=l.gems[0],p=l.players.find(p=>p.kind===g.kind);
    p.x=g.x-p.w/2;p.y=g.y-30;p.vx=p.vy=0;
    l.update(0);
    return {collected:g.got,feedback:l.feedback.length};
  });
  assert(collection.collected&&collection.feedback>0);
  for(let i=0;i<14;i++) await page.evaluate(i=>{Game.startLevel(i); Render.frame(Game.level,1/60)},i);
  const earned=await page.evaluate(()=>{
    Game.startLevel(0);const l=Game.level;l.gems.forEach(g=>g.got=true);l.time=10;l.deaths=0;l.done=true;UI.hud(l);
    Game.levelComplete(l);
    return {medals:Save.data.medals[0],stored:JSON.parse(localStorage.getItem(Save.key)).medals[0]};
  });
  assert.deepEqual(earned.medals,[true,true,true]);assert.deepEqual(earned.stored,[true,true,true]);
  await page.waitForFunction(()=>getComputedStyle(document.getElementById('ovWin')).opacity==='1');
  await page.screenshot({path:path.join(__dirname,'challenge-preview.png')});
  await page.evaluate(()=>{Game.startLevel(0);Game.level.deaths=2;Game.level.time=999;Game.levelComplete(Game.level)});
  assert.equal(await page.locator('.challenge.earned').count(),0);
  assert.deepEqual(await page.evaluate(()=>Save.data.medals[0]),[true,true,true]);
  await page.evaluate(()=>Game.toMap());assert.equal(await page.locator('.node .medals').first().textContent(),'◆ ✦ ◷');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.evaluate(()=>Render.frame(Game.level,1/60));
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>{Game.state='title';UI.show('ovTitle');Game.fit()});
  assert(await page.locator('#btnPlay').isVisible());
  assert.deepEqual(errors,[]);
  await page.evaluate(()=>Save.reset());assert.deepEqual(await page.evaluate(()=>Save.data.medals),{});
  console.log('PASS: assets, movement, swap, pause, hint toggle, crystal feedback, all 14 renders, medals earned/persisted/retained/reset, reduced motion, narrow viewport; no JS errors.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
